<html>
    <head>
        <title>
            Hello
        </title>
    </head>
    <body>
        <?php 
            echo"<h1>Hello</h1><br>";
            echo"<h2>Prachinburi</h2>";
        ?>
    </body>
</html>